<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 2                     */
/* CACHE FILE: Generated: Thu, 26 Apr 2007 20:47:14 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_trivia_2 {

 var $ipsclass;
//===========================================================================
// <ips:add_question_form:desc:>
//===========================================================================
function add_question_form() {
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class='borderwrap'>

 <div class='maintitle'>

  <p><{CAT_IMG}>&nbsp;{$this->ipsclass->lang['add_question_bar']}</p>

 </div>

 <form action="{$this->ipsclass->base_url}autocom=trivia&amp;CODE=doaddquestion" method='post' name='question'>

 <table cellpadding='4' cellspacing='1' border='0' width='100%'>

  <tr class='row\1'>

   <td width='20%'><b>{$this->ipsclass->lang['add_question']}:</b></td>

   <td width='80%'><input type='text' class='forminput' size='50' name='the_question' /></td>

  </tr>

  <tr class='row2'>

   <td width='20%'><b>{$this->ipsclass->lang['add_answer']}:</b></td>

   <td width='80%'><input type='text' class='forminput' size='50' name='the_answer' /></td>

  </tr>

  <tr class='row1'>

   <td width='20%'>&nbsp;</td>

   <td width='80%'><input type="submit" name="submit" value="{$this->ipsclass->lang['add_question_submit']}" /></td>

  </tr>

 </table>

 </form>

</div>

<br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:button_cont_c:desc:>
//===========================================================================
function button_cont_c() {
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<span class='fauxbutton'><a href="#" onclick="this.onclick='';document.forms['question'].submit();">{$this->ipsclass->lang['button_next']}</a></span>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:button_continue:desc:>
//===========================================================================
function button_continue() {
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<span class='fauxbutton'><a href='{$this->ipsclass->base_url}autocom=trivia&CODE=03'>{$this->ipsclass->lang['button_cont']}</a></span>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:button_finalize:desc:>
//===========================================================================
function button_finalize($type=0) {
$IPBHTML = "";
//--starthtml--//

//startif
if ( $type==0 )
{
$IPBHTML .= <<<EOF
<span class='fauxbutton'><a href='{$this->ipsclass->base_url}autocom=trivia&amp;CODE=04'>{$this->ipsclass->lang['button_end']}</a></span>
EOF;
}//endif
//startif
if ( $type==1 )
{
$IPBHTML .= <<<EOF
<input type='submit' onclick="document.forms['question'].andend.value='1';" value='{$this->ipsclass->lang['button_end']}' class='fauxbutton' />
EOF;
}//endif
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:button_new:desc:>
//===========================================================================
function button_new() {
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<span class='fauxbutton'><a href='{$this->ipsclass->base_url}autocom=trivia&amp;CODE=02'>{$this->ipsclass->lang['button_new']}</a></span>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:for_popup:desc:>
//===========================================================================
function for_popup($msg="") {
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class='borderwrap'>

 <div class='maintitle'>

  <p><{CAT_IMG}>&nbsp;{$this->ipsclass->lang['maintitle_bar']}</p>

 </div>

 <table cellpadding='4' cellspacing='1' border='0' width='100%'>

  <tr>

   <td class='row2' width='100%'>

    {$msg}

    </td>

   </tr>

 </table>

</div>

<br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:main_page_block:desc:>
//===========================================================================
function main_page_block($msg="") {
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class='borderwrap'>

 <div class='maintitle'>

   <p><{CAT_IMG}>&nbsp;{$this->ipsclass->lang['maintitle_bar']}</p>

 </div>

 <table width='100%' cellpadding='4' cellspacing='1' border='0'>

  <tr>

   <td class='row2' width='100%'>{$msg}</td>

  </tr>

 </table>

</div>

<br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:main_page_end:desc:>
//===========================================================================
function main_page_end($buttons=array()) {
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<br />
<center>{$buttons[0]}
EOF;
//startif
if ( $buttons[1] )
{
$IPBHTML .= <<<EOF
&nbsp;&nbsp;{$buttons[1]}
EOF;
}//endif
//startif
if ( $buttons[2] )
{
$IPBHTML .= <<<EOF
&nbsp;&nbsp;{$buttons[2]}
EOF;
}//endif
$IPBHTML .= <<<EOF
</center>
<br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mod_block_layout:desc:>
//===========================================================================
function mod_block_layout($block_new="",$block_hidden="") {
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<table width='100%' border='0' cellspacing='3' cellpadding='3'>

<tr>

 <td width='100%'><center><b><span style='font-size:12pt;'>{$this->ipsclass->lang['mod_title']}</span></b></center></td>

</tr>

<tr>

 <td width='100%'>{$block_new}</td>

</tr>

<tr>

 <td width='100%'>{$block_hidden}</td>

</tr>

</table>

<br /><br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:no_question_block:desc:>
//===========================================================================
function no_question_block() {
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class='borderwrap'>

 <div class='maintitle'>

   <p><{CAT_IMG}>&nbsp;{$this->ipsclass->lang['maintitle_bar']}</p>

 </div>

 <table width='100%' cellpadding='4' cellspacing='1' border='0'>

  <tr>

   <td class='row2' width='100%'>{$this->ipsclass->lang['no_questions']}</td>

  </tr>

 </table>

</div>

<br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:prev_question_block:desc:>
//===========================================================================
function prev_question_block($ques=array(),$mod="") {
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class='borderwrap'>
 <div class='maintitle'>
  <p><{CAT_IMG}>&nbsp;{$this->ipsclass->lang['maintitle_bar']}</p>
 </div>
 <table cellpadding='4' cellspacing='1' border='0' width='100%'>
  <tr>
   <td class='row2' width='100%'>
    <span style='font-size: 18px;'>{$this->ipsclass->lang['last_question']}:"{$ques['question']}"</span><br /><br />
EOF;
//startif
if ( $this->ipsclass->member['g_access_cp'] )
{
$IPBHTML .= <<<EOF
{$this->ipsclass->lang['hereis_answer']}:&nbsp;<b>{$ques['answer']}</b><br />
EOF;
}//endif
$IPBHTML .= <<<EOF
    {$this->ipsclass->lang['your_answer']}:&nbsp;{$ques['prev_ans']}<br />
    {$this->ipsclass->lang['answer_was']}&nbsp;{$ques['flag']}<br clear='all' /><br />
{$mod}
     </form>
    </td>
   </tr>
 </table>
</div>
<br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:question_block:desc:>
//===========================================================================
function question_block($ques=array()) {
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class='borderwrap'>
 <div class='maintitle'>
  <p><{CAT_IMG}>&nbsp;{$this->ipsclass->lang['maintitle_bar']}</p>
 </div>
 <table cellpadding='4' cellspacing='1' border='0' width='100%'>
  <tr>
   <td class='row2' width='100%'>
    <b>{$ques['question']}</b><br /><br />
    <form action="{$this->ipsclass->base_url}autocom=trivia&amp;CODE=03" method='post' name='question'>
    <input type="hidden" name="id" value="{$ques['id']}" />
    <input type='hidden' name='andend' value='0' />
    {$this->ipsclass->lang['enter_answer']}:&nbsp;<input type='text' class='forminput' size='50' name='the_answer' /><br />
     </form>
    </td>
   </tr>
 </table>
</div>
<br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:stat_block_end:desc:>
//===========================================================================
function stat_block_end() {
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
</table></div>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:stat_block_layout:desc:>
//===========================================================================
function stat_block_layout($b1="",$b2="",$b3="",$b4="") {
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<table width='100%' border='0' cellspacing='3' cellpadding='3'>
<tr>
 <td width='50%'>{$b1}</td>
 <td width='50%'>{$b2}</td>
</tr>
<tr>
 <td width='50%'>{$b3}</td>
 <td width='50%'>{$b4}</td>
</tr>
</table>
<br /><br />
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:stat_block_row:desc:>
//===========================================================================
function stat_block_row($r=array()) {
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<tr>
 <td class='row2'>{$r['mname']}</td><td class='row2'>{$r['data']}</td>
</tr>
EOF;

//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:stat_block_start:desc:>
//===========================================================================
function stat_block_start($lang="",$thlang="") {
$IPBHTML = "";
//--starthtml--//


$IPBHTML .= <<<EOF
<div class='borderwrap'>
 <div class='maintitle'>{$lang}</div>
 <table cellpadding='4' cellspacing='1' border='0' width='100%'>
  <tr>
   <th width='80%'>{$this->ipsclass->lang['stat_name']}</th>
   <th width='20%'>{$thlang}</th>
  </tr>
EOF;

//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>

</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>